# Generated by Django 6.0.5 on 2026-05-28 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='mis_a_jour_le',
        ),
        migrations.AlterField(
            model_name='produit',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.IntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fait_le', models.DateTimeField(auto_now_add=True)),
                ('fait_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='produits.produit')),
            ],
        ),
    ]
